Seperate client/server
tiago86g/Church pull request #10
Opened 2020-11-18 22:53 UTC by STEP0HEN

2020-11-18 23:14 UTC, tiago86g commented
The JSON is super nice but I guess you need to pull develop, the restructure of folders is already done like: 
client
    > components
    > containers 
          >(one folder for each page)
          ...
server
    > data

2020-11-18 23:36 UTC, STEP0HEN commented
Thanks for the quick review @tiago86g . I pulled from develop before starting to work, I just made changes to the already existing structure to add, server/data and I just merged develop.

2020-11-19 09:06 UTC, tiago86g requested changes
You just forgot to delete the folder "page" inside "components". The same content is already inside "containers" folder

2020-11-19 19:31 UTC, tiago86g approved these changes

2020-11-19 20:00 UTC, merged